export { RecorderHost } from './host'
export { registerRecorderIpc } from './ipc'
export type { RecorderIpcDeps } from './ipc'
export { RecorderSelectSession } from './session'
export type { RecorderSelectSessionDeps } from './session'
export { recorderFeature } from './feature'
export type { RecorderFeatureHandles, RecorderActions } from './feature'
