/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 同步采前台 hwnd；属于 ownPid 则返回 null */
export declare function captureForegroundHwnd(ownPid: number): string | null
/** hide 前放行目标抢焦点 */
export declare function prepareFocusHandoff(token: string): void
/** 句柄是否属于本进程 */
export declare function isOurProcessHwnd(token: string, ownPid: number): boolean
/** 当前前台是否属于本进程 */
export declare function isForegroundOurs(ownPid: number): boolean
/** 当前前台是否已是目标（或同进程窗） */
export declare function isForegroundTarget(token: string, ownPid: number): boolean
/** 激活目标窗口（Win：hwnd token；mac：bundle id） */
export declare function activateFocusTarget(token: string): boolean
/** 立刻模拟 Ctrl+V（Win）；不含延时 */
export declare function simulateCtrlV(): boolean
/** 本进程 bundle id */
export declare function getOwnBundleId(pid: number): string | null
/** 当前前台 bundle id */
export declare function getFrontmostBundleId(): string | null
/** 立刻模拟 ⌘V（mac）；不含延时 */
export declare function simulateCmdV(): boolean
