/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DeviceInfoJs {
  id: string
  name: string
  deviceType: string
  width: number
  height: number
  isPrimary: boolean
}
export interface RecordConfigJs {
  screenId?: string
  enableMic?: boolean
  enableSystemAudio?: boolean
  micDeviceId?: string
  systemDeviceId?: string
  fps?: number
  outputPath: string
  ffmpegPath?: string
}
/** 枚举显示器 */
export declare function listScreens(): Array<DeviceInfoJs>
/** 枚举麦克风 */
export declare function listMics(): Array<DeviceInfoJs>
/** 枚举系统声输出（环回） */
export declare function listSystemOutputs(): Array<DeviceInfoJs>
/** 注册事件回调 */
export declare function onEvent(callback: (...args: any[]) => any): void
/** 开始录制 */
export declare function startRecord(config: RecordConfigJs): void
/** 停止录制 */
export declare function stopRecord(): void
/** 当前状态 */
export declare function getState(): string
